spring.application.name=instituto
spring.datasource.url=jdbc:h2:mem:instituto
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

logging.level.org.hibernate.SQL=DEBUG


